Repository SSUDevelog/Velog-Android, pull requests merged in 2023-08, with the labels that each got.

#6 Feature/#4 google sign in
  app/build.gradle.kts
  buildSrc/src/main/java/Dependencies.kt
  buildSrc/src/main/java/Versions.kt
  presentation/build.gradle.kts
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/velogm/presentation/ui/SignInActivity.kt
  presentation/src/main/res/drawable/ic_google_logo.xml
  presentation/src/main/res/drawable/ic_logo.xml
  presentation/src/main/res/drawable/shape_white_fill_8_rect.xml
  presentation/src/main/res/layout/activity_sign_in.xml
  presentation/src/main/res/values/strings.xml
Labels: ✨ [FEAT], 👩‍👧‍👧 인디언 소현이

#15 [FEAT] : splash / #5
  buildSrc/src/main/java/Dependencies.kt
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/ic_launcher-playstore.png
  presentation/src/main/java/com/velogm/presentation/ui/SplashActivity.kt
  presentation/src/main/res/drawable-v24/ic_launcher_foreground.xml
  presentation/src/main/res/drawable/background_splash_screen.xml
  presentation/src/main/res/drawable/ic_launcher_foreground.xml
  presentation/src/main/res/drawable/ic_logo.xml
  presentation/src/main/res/drawable/img_logo.png
  presentation/src/main/res/drawable/img_logo_title.png
  presentation/src/main/res/layout/activity_sign_in.xml
  presentation/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  presentation/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  presentation/src/main/res/mipmap-anydpi-v33/ic_launcher.xml
  presentation/src/main/res/mipmap-hdpi/ic_launcher.png
  presentation/src/main/res/mipmap-hdpi/ic_launcher.webp
  presentation/src/main/res/mipmap-hdpi/ic_launcher_round.png
  presentation/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  presentation/src/main/res/mipmap-mdpi/ic_launcher.png
  presentation/src/main/res/mipmap-mdpi/ic_launcher.webp
  presentation/src/main/res/mipmap-mdpi/ic_launcher_round.png
  presentation/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  presentation/src/main/res/mipmap-xhdpi/ic_launcher.png
  presentation/src/main/res/mipmap-xhdpi/ic_launcher.webp
  presentation/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  presentation/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  presentation/src/main/res/mipmap-xxhdpi/ic_launcher.png
  presentation/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  presentation/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  presentation/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  presentation/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  presentation/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  presentation/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  presentation/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  presentation/src/main/res/values-v31/theme.xml
  presentation/src/main/res/values/ic_launcher_background.xml
  presentation/src/main/res/values/themes.xml
Labels: ✨ [FEAT], 👩‍👧‍👧 인디언 소현이

#17 Feature/#16 feat home tab
  app/src/main/java/com/velogandroid/di/ApiModule.kt
  app/src/main/java/com/velogandroid/di/DataSourceModule.kt
  app/src/main/java/com/velogandroid/di/RepoModule.kt
  app/src/main/java/com/velogandroid/di/UseCaseModule.kt
  data-remote/src/main/java/com/data_remote/api/HomeApiService.kt
  data-remote/src/main/java/com/data_remote/datasource/HomeDataSourceImpl.kt
  data/src/main/java/com/velogm/data/datasource/HomeDataSource.kt
  data/src/main/java/com/velogm/data/repositoryimpl/HomeRepositoryImpl.kt
  domain/src/main/java/com/velogm/domain/model/Tag.kt
  domain/src/main/java/com/velogm/domain/repository/HomeRepository.kt
  domain/src/main/java/com/velogm/domain/usecase/GetTagUseCase.kt
  presentation/src/main/java/com/velogm/presentation/mapper/TagMapper.kt
  presentation/src/main/java/com/velogm/presentation/model/TagModel.kt
  presentation/src/main/java/com/velogm/presentation/ui/SignInActivity.kt
  presentation/src/main/java/com/velogm/presentation/ui/home/HomeCollectionAdapter.kt
  presentation/src/main/java/com/velogm/presentation/ui/home/HomeFragment.kt
  presentation/src/main/java/com/velogm/presentation/ui/home/HomeViewModel.kt
  presentation/src/main/java/com/velogm/presentation/ui/home/ScreenHomeSlidePageFragment.kt
  presentation/src/main/res/color/selector_tablayout_text.xml
  presentation/src/main/res/drawable/ic_add.xml
  presentation/src/main/res/drawable/ic_search.xml
  presentation/src/main/res/font/font_pretendard_bold.xml
  presentation/src/main/res/font/font_pretendard_medium.xml
  presentation/src/main/res/font/pretendard_bold.otf
  presentation/src/main/res/font/pretendard_medium.otf
  presentation/src/main/res/layout/fragment_home.xml
  presentation/src/main/res/layout/item_fragment_home_.xml
  presentation/src/main/res/layout/item_rv_home_tag.xml
  presentation/src/main/res/values/appearances.xml
  presentation/src/main/res/values/strings.xml
Labels: ✨ [FEAT], 👩‍👧‍👧 인디언 삭

#23 Feature/#19 follow
  presentation/src/main/res/drawable/ic_bottom_sheet_follow_add.xml
  presentation/src/main/res/drawable/ic_bottom_sheet_follow_add_cancel.xml
  presentation/src/main/res/drawable/ic_bottom_sheet_follow_add_cancel_text.xml
  presentation/src/main/res/drawable/ic_follow_dialog.xml
  presentation/src/main/res/drawable/ic_follow_follower.xml
  presentation/src/main/res/drawable/ic_follow_reading_glasses.xml
  presentation/src/main/res/drawable/img_follow_empty.png
  presentation/src/main/res/drawable/shape_gray100_fill_4_rect.xml
  presentation/src/main/res/drawable/shape_gray100_fill_6_rect.xml
  presentation/src/main/res/drawable/shape_main_fill_20_rect.xml
  presentation/src/main/res/drawable/shape_white_fill_12_rect.xml
  presentation/src/main/res/layout/bottom_sheet_follow_add.xml
  presentation/src/main/res/layout/dialog_follow_cancel.xml
  presentation/src/main/res/layout/fragment_follow.xml
  presentation/src/main/res/layout/item_rv_follow.xml
  presentation/src/main/res/values/strings.xml
Labels: 💄 [UI], ✅ [MOD], 👩‍👧‍👧 인디언 소현이

#22 Feature/#21 home item
  app/src/main/java/com/velogandroid/di/ApiModule.kt
  app/src/main/java/com/velogandroid/di/DataSourceModule.kt
  app/src/main/java/com/velogandroid/di/RepoModule.kt
  app/src/main/java/com/velogandroid/di/UseCaseModule.kt
  data-remote/src/main/java/com/data_remote/api/SubscribeApiService.kt
  data-remote/src/main/java/com/data_remote/api/TagApiService.kt
  data-remote/src/main/java/com/data_remote/datasource/SubscribeDataSourceImpl.kt
  data-remote/src/main/java/com/data_remote/datasource/TagDataSourceImpl.kt
  data/src/main/java/com/velogm/data/datasource/SubscribeDataSource.kt
  data/src/main/java/com/velogm/data/datasource/TagDataSource.kt
  data/src/main/java/com/velogm/data/dto/response/PostListDto.kt
  data/src/main/java/com/velogm/data/repositoryimpl/SubscribeRepositoryImpl.kt
  data/src/main/java/com/velogm/data/repositoryimpl/TagRepositoryImpl.kt
  domain/src/main/java/com/velogm/domain/model/PostList.kt
  domain/src/main/java/com/velogm/domain/repository/SubscribeRepository.kt
  domain/src/main/java/com/velogm/domain/repository/TagRepository.kt
  domain/src/main/java/com/velogm/domain/usecase/GetFollowPostsUseCase.kt
  domain/src/main/java/com/velogm/domain/usecase/GetTagPostsUseCase.kt
  domain/src/main/java/com/velogm/domain/usecase/GetTrendPostUseCase.kt
  presentation/src/main/java/com/velogm/presentation/mapper/PostMapper.kt
  presentation/src/main/java/com/velogm/presentation/model/PostModelList.kt
  presentation/src/main/java/com/velogm/presentation/ui/home/HomeCollectionAdapter.kt
  presentation/src/main/java/com/velogm/presentation/ui/home/HomeFragment.kt
  presentation/src/main/java/com/velogm/presentation/ui/home/ScreenHomeSlidePageFragment.kt
  presentation/src/main/java/com/velogm/presentation/ui/home/screenhome/PostAdapter.kt
  presentation/src/main/java/com/velogm/presentation/ui/home/screenhome/ScreenHomeSlidePageFragment.kt
  presentation/src/main/java/com/velogm/presentation/ui/home/screenhome/ScreenViewModel.kt
  presentation/src/main/java/com/velogm/presentation/ui/home/screenhome/viewholder/PostViewHolder.kt
  presentation/src/main/java/com/velogm/presentation/util/BindingAdapter.kt
  presentation/src/main/res/drawable/ic_bookmark.xml
  presentation/src/main/res/layout/item_fragment_home_.xml
  presentation/src/main/res/layout/item_rv_post.xml
Labels: 💄 [UI], ✨ [FEAT], 👩‍👧‍👧 인디언 삭

#25 Feature/#24 UI search
  data/src/main/java/com/velogm/data/datasource/TagDataSource.kt
  domain/src/main/java/com/velogm/domain/repository/TagRepository.kt
  presentation/src/main/java/com/velogm/presentation/ui/SignInActivity.kt
  presentation/src/main/java/com/velogm/presentation/ui/SignInViewModel.kt
  presentation/src/main/java/com/velogm/presentation/ui/home/HomeFragment.kt
  presentation/src/main/java/com/velogm/presentation/ui/home/screenhome/PostAdapter.kt
  presentation/src/main/java/com/velogm/presentation/ui/home/screenhome/ScreenHomeSlidePageFragment.kt
  presentation/src/main/java/com/velogm/presentation/ui/home/search/SearchFragment.kt
  presentation/src/main/java/com/velogm/presentation/ui/home/search/SearchViewModel.kt
  presentation/src/main/res/drawable/shape_main_fill_16_rect.xml
  presentation/src/main/res/drawable/shape_white_fill_17_rect.xml
  presentation/src/main/res/layout/fragment_home_search.xml
  presentation/src/main/res/layout/item_home_search_tag.xml
  presentation/src/main/res/navigation/navigation_main.xml
  presentation/src/main/res/values/strings.xml
Labels: 🔨 [FIX], ✨ [FEAT], 👩‍👧‍👧 인디언 삭
