Repository SSUDevelog/Velog-Android, pull requests merged in 2023-10, with the labels that each got.

#34 Feature/#31 follower api
  .gitignore
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/velogandroid/di/UseCaseModule.kt
  app/src/main/java/com/velogandroid/service/VelogFirebaseMessagingService.kt
  build.gradle.kts
  buildSrc/src/main/java/Dependencies.kt
  buildSrc/src/main/java/Versions.kt
  data-remote/src/main/java/com/data_remote/api/SubscribeApiService.kt
  data-remote/src/main/java/com/data_remote/datasource/SubscribeDataSourceImpl.kt
  data/src/main/java/com/velogm/data/datasource/SubscribeDataSource.kt
  data/src/main/java/com/velogm/data/dto/response/FollowerDto.kt
  data/src/main/java/com/velogm/data/repositoryimpl/SubscribeRepositoryImpl.kt
  domain/src/main/java/com/velogm/domain/model/Follower.kt
  domain/src/main/java/com/velogm/domain/repository/SubscribeRepository.kt
  domain/src/main/java/com/velogm/domain/usecase/AddFollowerUseCase.kt
  domain/src/main/java/com/velogm/domain/usecase/GetInputFollowerUseCase.kt
  presentation/build.gradle.kts
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/velogm/presentation/mapper/FollowerNameMapper.kt
  presentation/src/main/java/com/velogm/presentation/model/FollowerNameList.kt
  presentation/src/main/java/com/velogm/presentation/ui/follow/AddFollowerFragment.kt
  presentation/src/main/java/com/velogm/presentation/ui/follow/AddFollowerViewModel.kt
  presentation/src/main/java/com/velogm/presentation/ui/follow/FollowFragment.kt
  presentation/src/main/java/com/velogm/presentation/ui/follow/FollowViewModel.kt
  presentation/src/main/java/com/velogm/presentation/ui/follow/viewholder/FollowerViewHolder.kt
  presentation/src/main/java/com/velogm/presentation/util/BindingAdapter.kt
  presentation/src/main/java/com/velogm/presentation/util/Constants.kt
  presentation/src/main/res/drawable/ic_add_follower_cancle.xml
  presentation/src/main/res/drawable/ic_bottom_sheet_follow_add.xml
  presentation/src/main/res/drawable/ic_bottom_sheet_follow_add_cancel.xml
  presentation/src/main/res/drawable/ic_bottom_sheet_follow_add_cancel_text.xml
  presentation/src/main/res/drawable/ic_follow_reading_glasses.xml
  presentation/src/main/res/drawable/img_add_follower_empty.png
  presentation/src/main/res/layout/fragment_add_follower.xml
  presentation/src/main/res/layout/fragment_follow.xml
  presentation/src/main/res/layout/item_rv_follow.xml
  presentation/src/main/res/menu/menu_main_nav.xml
  presentation/src/main/res/navigation/navigation_main.xml
  presentation/src/main/res/values/strings.xml
Labels: 💄 [UI], ✨ [FEAT], 👩‍👧‍👧 인디언 소현이

#37 Feature/#36 setting UI
  presentation/src/main/java/com/velogm/presentation/ui/setting/LogoutDialogFragment.kt
  presentation/src/main/java/com/velogm/presentation/ui/setting/SettingFragment.kt
  presentation/src/main/java/com/velogm/presentation/ui/setting/WithdrawalDialogFragment.kt
  presentation/src/main/res/layout/fragment_logout_dialog.xml
  presentation/src/main/res/layout/fragment_setting.xml
  presentation/src/main/res/layout/fragment_withdrawal_dialog.xml
  presentation/src/main/res/values/strings.xml
Labels: 💄 [UI], 👩‍👧‍👧 인디언 소현이

#42 Feature/#41 setting api
  app/src/main/java/com/velogandroid/di/UseCaseModule.kt
  data-local/src/main/java/com/velogm/data_local/datasource/SharedPreferencesDataSource.kt
  data-remote/src/main/java/com/data_remote/api/SignApiService.kt
  data-remote/src/main/java/com/data_remote/datasource/SignDataSourceImpl.kt
  data/src/main/java/com/velogm/data/datasource/SignDataSource.kt
  data/src/main/java/com/velogm/data/dto/response/WithdrawalDto.kt
  data/src/main/java/com/velogm/data/repositoryimpl/AuthRepositoryImpl.kt
  data/src/main/java/com/velogm/data/repositoryimpl/SignRepositoryImpl.kt
  domain/src/main/java/com/velogm/domain/model/Withdrawal.kt
  domain/src/main/java/com/velogm/domain/repository/AuthRepository.kt
  domain/src/main/java/com/velogm/domain/repository/SignRepository.kt
  domain/src/main/java/com/velogm/domain/usecase/PostWithdrawalUseCase.kt
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/velogm/presentation/ui/MainActivity.kt
  presentation/src/main/java/com/velogm/presentation/ui/SignInViewModel.kt
  presentation/src/main/java/com/velogm/presentation/ui/SplashActivity.kt
  presentation/src/main/java/com/velogm/presentation/ui/setting/SettingFragment.kt
  presentation/src/main/java/com/velogm/presentation/ui/signin/SignCheck.kt
  presentation/src/main/java/com/velogm/presentation/ui/signin/SignInActivity.kt
  presentation/src/main/java/com/velogm/presentation/ui/signin/SignViewModel.kt
Labels: ✨ [FEAT], 👩‍👧‍👧 인디언 소현이

#48 Feature/#46 setting follow qa
  app/src/main/java/com/velogandroid/di/UseCaseModule.kt
  data-remote/src/main/java/com/data_remote/api/SignApiService.kt
  data-remote/src/main/java/com/data_remote/datasource/SignDataSourceImpl.kt
  data/src/main/java/com/velogm/data/datasource/SignDataSource.kt
  data/src/main/java/com/velogm/data/dto/response/WithdrawalDto.kt
  data/src/main/java/com/velogm/data/repositoryimpl/SignRepositoryImpl.kt
  domain/src/main/java/com/velogm/domain/model/Withdrawal.kt
  domain/src/main/java/com/velogm/domain/repository/SignRepository.kt
  domain/src/main/java/com/velogm/domain/usecase/PostWithdrawalUseCase.kt
  presentation/src/main/java/com/velogm/presentation/ui/follow/AddFollowerFragment.kt
  presentation/src/main/java/com/velogm/presentation/ui/follow/FollowFragment.kt
  presentation/src/main/java/com/velogm/presentation/ui/signin/SignInActivity.kt
  presentation/src/main/java/com/velogm/presentation/ui/signin/SignViewModel.kt
  presentation/src/main/res/drawable/ic_loading_1.xml
  presentation/src/main/res/layout/fragment_add_follower.xml
  presentation/src/main/res/layout/fragment_follow.xml
  presentation/src/main/res/layout/view_progressbar.xml
  presentation/src/main/res/values/strings.xml
Labels: 🔨 [FIX], ✨ [FEAT], 👩‍👧‍👧 인디언 소현이

#52 [REFACTOR] : qa 반영 / #50
  presentation/src/main/res/drawable/ic_add_follower_empty.xml
  presentation/src/main/res/drawable/ic_follow_empty.xml
  presentation/src/main/res/drawable/img_add_follower_empty.png
  presentation/src/main/res/drawable/img_follow_empty.png
  presentation/src/main/res/layout/activity_main.xml
  presentation/src/main/res/layout/empty_follow.xml
  presentation/src/main/res/layout/fragment_add_follower.xml
  presentation/src/main/res/layout/fragment_delete_follow_dialog.xml
  presentation/src/main/res/layout/fragment_follow.xml
  presentation/src/main/res/layout/fragment_home.xml
  presentation/src/main/res/layout/fragment_logout_dialog.xml
  presentation/src/main/res/layout/fragment_setting.xml
  presentation/src/main/res/layout/fragment_withdrawal_dialog.xml
Labels:  ♻️ [REFACTOR], 👩‍👧‍👧 인디언 소현이

#53 Feature/#51 qa fix
  core-ui/build.gradle.kts
  data/src/main/java/com/velogm/data/TokenInterceptor.kt
  presentation/src/main/java/com/velogm/presentation/ui/home/HomeFragment.kt
  presentation/src/main/java/com/velogm/presentation/ui/home/screenhome/ScreenHomeSlidePageFragment.kt
  presentation/src/main/res/drawable/ic_search_gray.xml
  presentation/src/main/res/drawable/loading01.xml
  presentation/src/main/res/layout/fragment_add_tag.xml
  presentation/src/main/res/layout/fragment_home.xml
  presentation/src/main/res/layout/fragment_home_search.xml
  presentation/src/main/res/layout/item_fragment_home_.xml
  presentation/src/main/res/values/strings.xml
Labels: 💄 [UI], 👩‍👧‍👧 인디언 삭
